development:
  mode: sandbox
  client_id: <%= ENV.fetch('PAYPAL_CLIENT_ID', 'sandbox_client_id') %>
  client_secret: <%= ENV.fetch('PAYPAL_SECRET', 'sandbox_client_secret') %>
  sandbox_email_address: <%= ENV['PAYPAL_SANDBOX'] %>

test:
  mode: sandbox
  client_id: <%= ENV.fetch('PAYPAL_CLIENT_ID', 'sandbox_client_id') %>
  client_secret: <%= ENV.fetch('PAYPAL_SECRET', 'sandbox_client_secret') %>
  sandbox_email_address: <%= ENV['PAYPAL_SANDBOX'] %>

production:
  mode: live
  client_id: <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_SECRET'] %>
  ssl_options:
    ca_file: null
